name: Deploy Strapi

on:
  push:
    branches:
      - main  # Запускати workflow при пушах до гілки main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Клонування репозиторію
      - name: Checkout repository
        uses: actions/checkout@v4

      # Встановлення SSH-клієнта
      #- name: Install SSH client
      #  run: sudo apt-get update && sudo apt-get install -y sshpass

      # Виконання команд на сервері
      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Stopping Strapi service..."
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S systemctl stop strapi

            cd /home/max/simpatik-group-strapi || exit

            if [ -d "dist" ]; then
              echo "Removing dist directory..."
              rm -rf dist
            else
              echo "dist directory does not exist. Skipping removal."
            fi

            echo "Reset local changes..."
            git reset --hard

            echo "Pulling latest version from Git..."
            git pull

            echo "Installing dependencies..."
            npm install -y

            echo "Building project..."
            npm run build

            echo "Starting Strapi service..."
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S systemctl start strapi

            echo "Deployment completed successfully!"